services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    platform: linux/amd64
    container_name: valheim
    cap_add:
      - sys_nice
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    ports:
      - '2456-2458:2456-2458/udp'
      - '9001:9001/tcp'
      - '8080:8080/tcp'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SUPERVISOR_HTTP_PASS=${SUPERVISOR_HTTP_PASS}
      - SERVER_PASS=${VALHEIM_SERVER_PASS}
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-volume:/data
    restart: always

  mqtt:
    build: .
    container_name: mqtt_sub
    depends_on:
      - redis
    environment:
      - PERMITTED_FILE=config/permittedlist.txt
      - TZ=America/Sao_Paulo
      - CLIENT_ID=${MQTT_CLIENT_ID}
      - HOST=${MQTT_HOST}
      - USERNAME=${MQTT_USERNAME}
      - PASSWORD=${MQTT_PASSWORD}
    volumes:
      - ./:/code
      - /code/.venv
    restart: always
