version = 0.1
[default.deploy.parameters]
stack_name = "coffeeheim"
resolve_s3 = true
s3_prefix = "coffeeheim"
region = "sa-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []