on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [16.x]
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        working-directory: ./app
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npx wrangler pages deploy --project-name coffeeheim build/

  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60
    defaults:
      run:

    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        working-directory: ./ws
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
