on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    defaults:
      run:
        working-directory: ./app
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [16.x]
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npx wrangler pages deploy --project-name coffeeheim build/

  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - run: sam build --use-container
      - run: sam deploy
